### ISSUE TITLE
Pas de doc. d'installation

### ISSUE THREAD

**Issue by jframiara** [AP-Resto/Site-Resto#1]
On ne sait pas comment installer l'application.
Il faudrait expliquer :
-  ce qu'il faut copier dans le PHP,
-  comment paramétrer l'app. (user, base,...),
-  comment installer la base de données.

**Comment by WelsyMC** [comment]
Bonjour, la documentation a été ajoutée dans le commit **"Ajout du .sql de la base + la documentation + lien vers la documentation technique"**
